---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{id}":
    post:
      summary: Creates a comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: comment created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
          application/xml:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/v1/users/{user_id}/posts":
    get:
      summary: Retrieves posts comments
      tags:
      - Comments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: comments found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
                  author:
                    type: object
                  comments:
                    type: object
                    properties:
                      id:
                        type: integer
                      text:
                        type: string
                required:
                - id
                - title
                - comments
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
                  author:
                    type: object
                  comments:
                    type: object
                    properties:
                      id:
                        type: integer
                      text:
                        type: string
                required:
                - id
                - title
                - comments
        '404':
          description: comments not found
  "/api/v1/users/{id}":
    get:
      summary: Retrieves a user's posts
      tags:
      - Posts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  bio:
                    type: string
                  photo:
                    type: string
                  posts:
                    type: object
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                      text:
                        type: string
                required:
                - id
                - name
                - posts
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  bio:
                    type: string
                  photo:
                    type: string
                  posts:
                    type: object
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                      text:
                        type: string
                required:
                - id
                - name
                - posts
        '404':
          description: user not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
